workflows:
  ios-workflow:
    name: MorningRoutine iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    integrations:
      app_store_connect: Morning Routine API
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.morningRoutine
      vars:
        XCODE_PROJECT: "MorningRoutine.xcodeproj"
        XCODE_SCHEME: "MorningRoutine"
        APP_STORE_APP_ID: 6757846912
      xcode: 16.2
    scripts:
      - name: Set up code signing settings on Xcode project
        script: |
          xcode-project use-profiles
      - name: Increment build number
        script: |
          cd $CM_BUILD_DIR
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-testflight-build-number "$APP_STORE_APP_ID" || echo "0")
          echo "Latest build number from TestFlight: $LATEST_BUILD_NUMBER"
          NEW_BUILD_NUMBER=$(($LATEST_BUILD_NUMBER + 1))
          echo "Setting new build number: $NEW_BUILD_NUMBER"
          agvtool new-version -all $NEW_BUILD_NUMBER
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - superhuman555@gmail.com
        notify:
          success: true
          failure: true
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        submit_to_app_store: false
