-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgL4fkU74hWgqmYdz7
/ffDytB+pDYZt/bGJX1x4ZYAkRSgCgYIKoZIzj0DAQehRANCAASHJZ2hfM5uGQ+i
75wFFSZjP7vRlDDWje9X5Udj/jnX8QonQaGGlktreABbLalszyT9/qmVkNa7T47g
TAkGdpAD
-----END PRIVATE KEY-----